include: package:very_good_analysis/analysis_options.5.1.0.yaml
analyzer:
  exclude:
    - '**.freezed.dart'
    - '**.g.dart'
    - '**.gr.dart'
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    avoid_positional_boolean_parameters: false
    constant_identifier_names: false
    one_member_abstracts: false