targets:
  spendly:
    sources:
      - lib/**
      - $package$
    builders:
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/**/**_page.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/app/router/app_router.dart
